version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=eventsphere
      - POSTGRES_USER=user_eventsphere
      - POSTGRES_PASSWORD=event123
    ports:
      - 5432:5432